config/routes.rb
Rails.application.routes.draw do
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "root#index"

  get "up" => "rails/health#show", as: :rails_health_check

  resource  :session, only: %i[create destroy]
  resource  :wallet, only: :show, controller: "wallet"


  namespace :api do
    namespace :v1 do
      resources :users, only: [ :show ], param: :eth_address
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="dark" lang="en">
  <head>
    <title><%= content_for(:title) || "Blockchain Auth" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Blockchain Auth">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="turbo-refresh-method" content="morph">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    
    <%= render 'shared/favicons' %>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="min-h-screen bg-background text-foreground antialiased font-sans" 
        data-controller="navbar <%= 'wallet-login' unless Current.user %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/sidebar' %>

    <!-- Flash Notifications -->
    <div id="flash-section">
      <%= render 'layouts/shared/flash_messages' %>
    </div>

    <main class="container mx-auto max-w-4xl px-4 py-8 space-y-8">
      <%= yield %>
    </main>
  </body>
</html>